// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	url_domain "github.com/sinon273/url-shortener/url/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountActiveByUser provides a mock function with given fields: ctx, userID
func (_m *MockRepository) CountActiveByUser(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveByUser'
type MockRepository_CountActiveByUser_Call struct {
	*mock.Call
}

// CountActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) CountActiveByUser(ctx interface{}, userID interface{}) *MockRepository_CountActiveByUser_Call {
	return &MockRepository_CountActiveByUser_Call{Call: _e.mock.On("CountActiveByUser", ctx, userID)}
}

func (_c *MockRepository_CountActiveByUser_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_CountActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_CountActiveByUser_Call) Return(_a0 int, _a1 error) *MockRepository_CountActiveByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountActiveByUser_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRepository_CountActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, link
func (_m *MockRepository) Create(ctx context.Context, link url_domain.Link) error {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, url_domain.Link) error); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - link url_domain.Link
func (_e *MockRepository_Expecter) Create(ctx interface{}, link interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, link)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, link url_domain.Link)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(url_domain.Link))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, url_domain.Link) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByShortCode provides a mock function with given fields: ctx, shortCode
func (_m *MockRepository) DeleteByShortCode(ctx context.Context, shortCode string) error {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByShortCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByShortCode'
type MockRepository_DeleteByShortCode_Call struct {
	*mock.Call
}

// DeleteByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockRepository_Expecter) DeleteByShortCode(ctx interface{}, shortCode interface{}) *MockRepository_DeleteByShortCode_Call {
	return &MockRepository_DeleteByShortCode_Call{Call: _e.mock.On("DeleteByShortCode", ctx, shortCode)}
}

func (_c *MockRepository_DeleteByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *MockRepository_DeleteByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteByShortCode_Call) Return(_a0 error) *MockRepository_DeleteByShortCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteByShortCode_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByShortCode provides a mock function with given fields: ctx, shortCode
func (_m *MockRepository) GetByShortCode(ctx context.Context, shortCode string) (url_domain.Link, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortCode")
	}

	var r0 url_domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (url_domain.Link, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) url_domain.Link); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(url_domain.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByShortCode'
type MockRepository_GetByShortCode_Call struct {
	*mock.Call
}

// GetByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockRepository_Expecter) GetByShortCode(ctx interface{}, shortCode interface{}) *MockRepository_GetByShortCode_Call {
	return &MockRepository_GetByShortCode_Call{Call: _e.mock.On("GetByShortCode", ctx, shortCode)}
}

func (_c *MockRepository_GetByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *MockRepository_GetByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByShortCode_Call) Return(_a0 url_domain.Link, _a1 error) *MockRepository_GetByShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByShortCode_Call) RunAndReturn(run func(context.Context, string) (url_domain.Link, error)) *MockRepository_GetByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, limit, cursor
func (_m *MockRepository) ListByUser(ctx context.Context, userID string, limit int, cursor string) ([]url_domain.Link, string, error) {
	ret := _m.Called(ctx, userID, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []url_domain.Link
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) ([]url_domain.Link, string, error)); ok {
		return rf(ctx, userID, limit, cursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) []url_domain.Link); ok {
		r0 = rf(ctx, userID, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]url_domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) string); ok {
		r1 = rf(ctx, userID, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, string) error); ok {
		r2 = rf(ctx, userID, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - cursor string
func (_e *MockRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, limit interface{}, cursor interface{}) *MockRepository_ListByUser_Call {
	return &MockRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, limit, cursor)}
}

func (_c *MockRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string, limit int, cursor string)) *MockRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_ListByUser_Call) Return(_a0 []url_domain.Link, _a1 string, _a2 error) *MockRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_ListByUser_Call) RunAndReturn(run func(context.Context, string, int, string) ([]url_domain.Link, string, error)) *MockRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
