// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserClient is an autogenerated mock type for the UserClient type
type MockUserClient struct {
	mock.Mock
}

type MockUserClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserClient) EXPECT() *MockUserClient_Expecter {
	return &MockUserClient_Expecter{mock: &_m.Mock}
}

// GetLimit provides a mock function with given fields: ctx, userID
func (_m *MockUserClient) GetLimit(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLimit")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserClient_GetLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimit'
type MockUserClient_GetLimit_Call struct {
	*mock.Call
}

// GetLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserClient_Expecter) GetLimit(ctx interface{}, userID interface{}) *MockUserClient_GetLimit_Call {
	return &MockUserClient_GetLimit_Call{Call: _e.mock.On("GetLimit", ctx, userID)}
}

func (_c *MockUserClient_GetLimit_Call) Run(run func(ctx context.Context, userID string)) *MockUserClient_GetLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserClient_GetLimit_Call) Return(_a0 int, _a1 error) *MockUserClient_GetLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserClient_GetLimit_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockUserClient_GetLimit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserClient creates a new instance of MockUserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserClient {
	mock := &MockUserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
