// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// DecrCounter provides a mock function with given fields: ctx, userID
func (_m *MockCache) DecrCounter(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DecrCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_DecrCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrCounter'
type MockCache_DecrCounter_Call struct {
	*mock.Call
}

// DecrCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCache_Expecter) DecrCounter(ctx interface{}, userID interface{}) *MockCache_DecrCounter_Call {
	return &MockCache_DecrCounter_Call{Call: _e.mock.On("DecrCounter", ctx, userID)}
}

func (_c *MockCache_DecrCounter_Call) Run(run func(ctx context.Context, userID string)) *MockCache_DecrCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_DecrCounter_Call) Return(_a0 error) *MockCache_DecrCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_DecrCounter_Call) RunAndReturn(run func(context.Context, string) error) *MockCache_DecrCounter_Call {
	_c.Call.Return(run)
	return _c
}

// DelLink provides a mock function with given fields: ctx, shortCode
func (_m *MockCache) DelLink(ctx context.Context, shortCode string) error {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for DelLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_DelLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelLink'
type MockCache_DelLink_Call struct {
	*mock.Call
}

// DelLink is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockCache_Expecter) DelLink(ctx interface{}, shortCode interface{}) *MockCache_DelLink_Call {
	return &MockCache_DelLink_Call{Call: _e.mock.On("DelLink", ctx, shortCode)}
}

func (_c *MockCache_DelLink_Call) Run(run func(ctx context.Context, shortCode string)) *MockCache_DelLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_DelLink_Call) Return(_a0 error) *MockCache_DelLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_DelLink_Call) RunAndReturn(run func(context.Context, string) error) *MockCache_DelLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetCounter provides a mock function with given fields: ctx, userID
func (_m *MockCache) GetCounter(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCounter")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_GetCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCounter'
type MockCache_GetCounter_Call struct {
	*mock.Call
}

// GetCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCache_Expecter) GetCounter(ctx interface{}, userID interface{}) *MockCache_GetCounter_Call {
	return &MockCache_GetCounter_Call{Call: _e.mock.On("GetCounter", ctx, userID)}
}

func (_c *MockCache_GetCounter_Call) Run(run func(ctx context.Context, userID string)) *MockCache_GetCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_GetCounter_Call) Return(_a0 int, _a1 error) *MockCache_GetCounter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_GetCounter_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockCache_GetCounter_Call {
	_c.Call.Return(run)
	return _c
}

// GetLimit provides a mock function with given fields: ctx, userID
func (_m *MockCache) GetLimit(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLimit")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_GetLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimit'
type MockCache_GetLimit_Call struct {
	*mock.Call
}

// GetLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCache_Expecter) GetLimit(ctx interface{}, userID interface{}) *MockCache_GetLimit_Call {
	return &MockCache_GetLimit_Call{Call: _e.mock.On("GetLimit", ctx, userID)}
}

func (_c *MockCache_GetLimit_Call) Run(run func(ctx context.Context, userID string)) *MockCache_GetLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_GetLimit_Call) Return(_a0 int, _a1 error) *MockCache_GetLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_GetLimit_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockCache_GetLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetLink provides a mock function with given fields: ctx, shortCode
func (_m *MockCache) GetLink(ctx context.Context, shortCode string) (string, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_GetLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLink'
type MockCache_GetLink_Call struct {
	*mock.Call
}

// GetLink is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockCache_Expecter) GetLink(ctx interface{}, shortCode interface{}) *MockCache_GetLink_Call {
	return &MockCache_GetLink_Call{Call: _e.mock.On("GetLink", ctx, shortCode)}
}

func (_c *MockCache_GetLink_Call) Run(run func(ctx context.Context, shortCode string)) *MockCache_GetLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_GetLink_Call) Return(_a0 string, _a1 error) *MockCache_GetLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_GetLink_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCache_GetLink_Call {
	_c.Call.Return(run)
	return _c
}

// IncrCounter provides a mock function with given fields: ctx, userID
func (_m *MockCache) IncrCounter(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IncrCounter")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_IncrCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrCounter'
type MockCache_IncrCounter_Call struct {
	*mock.Call
}

// IncrCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCache_Expecter) IncrCounter(ctx interface{}, userID interface{}) *MockCache_IncrCounter_Call {
	return &MockCache_IncrCounter_Call{Call: _e.mock.On("IncrCounter", ctx, userID)}
}

func (_c *MockCache_IncrCounter_Call) Run(run func(ctx context.Context, userID string)) *MockCache_IncrCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_IncrCounter_Call) Return(_a0 int, _a1 error) *MockCache_IncrCounter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_IncrCounter_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockCache_IncrCounter_Call {
	_c.Call.Return(run)
	return _c
}

// SetCounter provides a mock function with given fields: ctx, userID, counter
func (_m *MockCache) SetCounter(ctx context.Context, userID string, counter int) error {
	ret := _m.Called(ctx, userID, counter)

	if len(ret) == 0 {
		panic("no return value specified for SetCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, userID, counter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_SetCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCounter'
type MockCache_SetCounter_Call struct {
	*mock.Call
}

// SetCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - counter int
func (_e *MockCache_Expecter) SetCounter(ctx interface{}, userID interface{}, counter interface{}) *MockCache_SetCounter_Call {
	return &MockCache_SetCounter_Call{Call: _e.mock.On("SetCounter", ctx, userID, counter)}
}

func (_c *MockCache_SetCounter_Call) Run(run func(ctx context.Context, userID string, counter int)) *MockCache_SetCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockCache_SetCounter_Call) Return(_a0 error) *MockCache_SetCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetCounter_Call) RunAndReturn(run func(context.Context, string, int) error) *MockCache_SetCounter_Call {
	_c.Call.Return(run)
	return _c
}

// SetLimit provides a mock function with given fields: ctx, userID, limit, ttl
func (_m *MockCache) SetLimit(ctx context.Context, userID string, limit int, ttl time.Duration) error {
	ret := _m.Called(ctx, userID, limit, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, time.Duration) error); ok {
		r0 = rf(ctx, userID, limit, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_SetLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLimit'
type MockCache_SetLimit_Call struct {
	*mock.Call
}

// SetLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - ttl time.Duration
func (_e *MockCache_Expecter) SetLimit(ctx interface{}, userID interface{}, limit interface{}, ttl interface{}) *MockCache_SetLimit_Call {
	return &MockCache_SetLimit_Call{Call: _e.mock.On("SetLimit", ctx, userID, limit, ttl)}
}

func (_c *MockCache_SetLimit_Call) Run(run func(ctx context.Context, userID string, limit int, ttl time.Duration)) *MockCache_SetLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCache_SetLimit_Call) Return(_a0 error) *MockCache_SetLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetLimit_Call) RunAndReturn(run func(context.Context, string, int, time.Duration) error) *MockCache_SetLimit_Call {
	_c.Call.Return(run)
	return _c
}

// SetLink provides a mock function with given fields: ctx, shortCode, originalURL, ttl
func (_m *MockCache) SetLink(ctx context.Context, shortCode string, originalURL string, ttl time.Duration) error {
	ret := _m.Called(ctx, shortCode, originalURL, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, shortCode, originalURL, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_SetLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLink'
type MockCache_SetLink_Call struct {
	*mock.Call
}

// SetLink is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - originalURL string
//   - ttl time.Duration
func (_e *MockCache_Expecter) SetLink(ctx interface{}, shortCode interface{}, originalURL interface{}, ttl interface{}) *MockCache_SetLink_Call {
	return &MockCache_SetLink_Call{Call: _e.mock.On("SetLink", ctx, shortCode, originalURL, ttl)}
}

func (_c *MockCache_SetLink_Call) Run(run func(ctx context.Context, shortCode string, originalURL string, ttl time.Duration)) *MockCache_SetLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCache_SetLink_Call) Return(_a0 error) *MockCache_SetLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetLink_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockCache_SetLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
