// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	session_domain "github.com/sinon273/url-shortener/user/internal/domain/session"
	mock "github.com/stretchr/testify/mock"

	time "time"

	user_domain "github.com/sinon273/url-shortener/user/internal/domain/user"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, userID, expiresAt
func (_m *MockRepository) CreateSession(ctx context.Context, userID string, expiresAt time.Time) (string, error) {
	ret := _m.Called(ctx, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (string, error)); ok {
		return rf(ctx, userID, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) string); ok {
		r0 = rf(ctx, userID, expiresAt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, userID, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - expiresAt time.Time
func (_e *MockRepository_Expecter) CreateSession(ctx interface{}, userID interface{}, expiresAt interface{}) *MockRepository_CreateSession_Call {
	return &MockRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, expiresAt)}
}

func (_c *MockRepository_CreateSession_Call) Run(run func(ctx context.Context, userID string, expiresAt time.Time)) *MockRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_CreateSession_Call) Return(_a0 string, _a1 error) *MockRepository_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateSession_Call) RunAndReturn(run func(context.Context, string, time.Time) (string, error)) *MockRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithSubscription provides a mock function with given fields: ctx, email, passwordHash
func (_m *MockRepository) CreateUserWithSubscription(ctx context.Context, email string, passwordHash string) (string, error) {
	ret := _m.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithSubscription")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, passwordHash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateUserWithSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithSubscription'
type MockRepository_CreateUserWithSubscription_Call struct {
	*mock.Call
}

// CreateUserWithSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
func (_e *MockRepository_Expecter) CreateUserWithSubscription(ctx interface{}, email interface{}, passwordHash interface{}) *MockRepository_CreateUserWithSubscription_Call {
	return &MockRepository_CreateUserWithSubscription_Call{Call: _e.mock.On("CreateUserWithSubscription", ctx, email, passwordHash)}
}

func (_c *MockRepository_CreateUserWithSubscription_Call) Run(run func(ctx context.Context, email string, passwordHash string)) *MockRepository_CreateUserWithSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_CreateUserWithSubscription_Call) Return(_a0 string, _a1 error) *MockRepository_CreateUserWithSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateUserWithSubscription_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockRepository_CreateUserWithSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, sessionID
func (_m *MockRepository) GetSession(ctx context.Context, sessionID string) (session_domain.Session, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 session_domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (session_domain.Session, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) session_domain.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(session_domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockRepository_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockRepository_GetSession_Call {
	return &MockRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockRepository_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetSession_Call) Return(_a0 session_domain.Session, _a1 error) *MockRepository_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSession_Call) RunAndReturn(run func(context.Context, string) (session_domain.Session, error)) *MockRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionLimit provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetSubscriptionLimit(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionLimit")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSubscriptionLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionLimit'
type MockRepository_GetSubscriptionLimit_Call struct {
	*mock.Call
}

// GetSubscriptionLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetSubscriptionLimit(ctx interface{}, userID interface{}) *MockRepository_GetSubscriptionLimit_Call {
	return &MockRepository_GetSubscriptionLimit_Call{Call: _e.mock.On("GetSubscriptionLimit", ctx, userID)}
}

func (_c *MockRepository_GetSubscriptionLimit_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetSubscriptionLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetSubscriptionLimit_Call) Return(_a0 int, _a1 error) *MockRepository_GetSubscriptionLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSubscriptionLimit_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRepository_GetSubscriptionLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetUserByEmail(ctx context.Context, email string) (user_domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 user_domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (user_domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) user_domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(user_domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockRepository_GetUserByEmail_Call {
	return &MockRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) Return(_a0 user_domain.User, _a1 error) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (user_domain.User, error)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, sessionID
func (_m *MockRepository) RevokeSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockRepository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockRepository_Expecter) RevokeSession(ctx interface{}, sessionID interface{}) *MockRepository_RevokeSession_Call {
	return &MockRepository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID)}
}

func (_c *MockRepository_RevokeSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockRepository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_RevokeSession_Call) Return(_a0 error) *MockRepository_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RevokeSession_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
