// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// DelSession provides a mock function with given fields: ctx, sessionID
func (_m *MockCache) DelSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DelSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_DelSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelSession'
type MockCache_DelSession_Call struct {
	*mock.Call
}

// DelSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockCache_Expecter) DelSession(ctx interface{}, sessionID interface{}) *MockCache_DelSession_Call {
	return &MockCache_DelSession_Call{Call: _e.mock.On("DelSession", ctx, sessionID)}
}

func (_c *MockCache_DelSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockCache_DelSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_DelSession_Call) Return(_a0 error) *MockCache_DelSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_DelSession_Call) RunAndReturn(run func(context.Context, string) error) *MockCache_DelSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, sessionID
func (_m *MockCache) GetSession(ctx context.Context, sessionID string) (string, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockCache_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockCache_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockCache_GetSession_Call {
	return &MockCache_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockCache_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockCache_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_GetSession_Call) Return(_a0 string, _a1 error) *MockCache_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_GetSession_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCache_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// SetSession provides a mock function with given fields: ctx, sessionID, userID, ttl
func (_m *MockCache) SetSession(ctx context.Context, sessionID string, userID string, ttl time.Duration) error {
	ret := _m.Called(ctx, sessionID, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, sessionID, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_SetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSession'
type MockCache_SetSession_Call struct {
	*mock.Call
}

// SetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - userID string
//   - ttl time.Duration
func (_e *MockCache_Expecter) SetSession(ctx interface{}, sessionID interface{}, userID interface{}, ttl interface{}) *MockCache_SetSession_Call {
	return &MockCache_SetSession_Call{Call: _e.mock.On("SetSession", ctx, sessionID, userID, ttl)}
}

func (_c *MockCache_SetSession_Call) Run(run func(ctx context.Context, sessionID string, userID string, ttl time.Duration)) *MockCache_SetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCache_SetSession_Call) Return(_a0 error) *MockCache_SetSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetSession_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockCache_SetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
