// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// AccessTTL provides a mock function with no fields
func (_m *MockAuth) AccessTTL() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessTTL")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockAuth_AccessTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessTTL'
type MockAuth_AccessTTL_Call struct {
	*mock.Call
}

// AccessTTL is a helper method to define mock.On call
func (_e *MockAuth_Expecter) AccessTTL() *MockAuth_AccessTTL_Call {
	return &MockAuth_AccessTTL_Call{Call: _e.mock.On("AccessTTL")}
}

func (_c *MockAuth_AccessTTL_Call) Run(run func()) *MockAuth_AccessTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuth_AccessTTL_Call) Return(_a0 time.Duration) *MockAuth_AccessTTL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuth_AccessTTL_Call) RunAndReturn(run func() time.Duration) *MockAuth_AccessTTL_Call {
	_c.Call.Return(run)
	return _c
}

// ComparePassword provides a mock function with given fields: hash, password
func (_m *MockAuth) ComparePassword(hash string, password string) error {
	ret := _m.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for ComparePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hash, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuth_ComparePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePassword'
type MockAuth_ComparePassword_Call struct {
	*mock.Call
}

// ComparePassword is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockAuth_Expecter) ComparePassword(hash interface{}, password interface{}) *MockAuth_ComparePassword_Call {
	return &MockAuth_ComparePassword_Call{Call: _e.mock.On("ComparePassword", hash, password)}
}

func (_c *MockAuth_ComparePassword_Call) Run(run func(hash string, password string)) *MockAuth_ComparePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuth_ComparePassword_Call) Return(_a0 error) *MockAuth_ComparePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuth_ComparePassword_Call) RunAndReturn(run func(string, string) error) *MockAuth_ComparePassword_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function with given fields: password
func (_m *MockAuth) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuth_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockAuth_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockAuth_Expecter) HashPassword(password interface{}) *MockAuth_HashPassword_Call {
	return &MockAuth_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockAuth_HashPassword_Call) Run(run func(password string)) *MockAuth_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuth_HashPassword_Call) Return(_a0 string, _a1 error) *MockAuth_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuth_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *MockAuth_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function with given fields: token
func (_m *MockAuth) Parse(token string) (string, string, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuth_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockAuth_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - token string
func (_e *MockAuth_Expecter) Parse(token interface{}) *MockAuth_Parse_Call {
	return &MockAuth_Parse_Call{Call: _e.mock.On("Parse", token)}
}

func (_c *MockAuth_Parse_Call) Run(run func(token string)) *MockAuth_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuth_Parse_Call) Return(_a0 string, _a1 string, _a2 error) *MockAuth_Parse_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuth_Parse_Call) RunAndReturn(run func(string) (string, string, error)) *MockAuth_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTTL provides a mock function with no fields
func (_m *MockAuth) RefreshTTL() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshTTL")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockAuth_RefreshTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTTL'
type MockAuth_RefreshTTL_Call struct {
	*mock.Call
}

// RefreshTTL is a helper method to define mock.On call
func (_e *MockAuth_Expecter) RefreshTTL() *MockAuth_RefreshTTL_Call {
	return &MockAuth_RefreshTTL_Call{Call: _e.mock.On("RefreshTTL")}
}

func (_c *MockAuth_RefreshTTL_Call) Run(run func()) *MockAuth_RefreshTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuth_RefreshTTL_Call) Return(_a0 time.Duration) *MockAuth_RefreshTTL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuth_RefreshTTL_Call) RunAndReturn(run func() time.Duration) *MockAuth_RefreshTTL_Call {
	_c.Call.Return(run)
	return _c
}

// SignAccess provides a mock function with given fields: userID, sessionID
func (_m *MockAuth) SignAccess(userID string, sessionID string) (string, error) {
	ret := _m.Called(userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for SignAccess")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(userID, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuth_SignAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignAccess'
type MockAuth_SignAccess_Call struct {
	*mock.Call
}

// SignAccess is a helper method to define mock.On call
//   - userID string
//   - sessionID string
func (_e *MockAuth_Expecter) SignAccess(userID interface{}, sessionID interface{}) *MockAuth_SignAccess_Call {
	return &MockAuth_SignAccess_Call{Call: _e.mock.On("SignAccess", userID, sessionID)}
}

func (_c *MockAuth_SignAccess_Call) Run(run func(userID string, sessionID string)) *MockAuth_SignAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuth_SignAccess_Call) Return(_a0 string, _a1 error) *MockAuth_SignAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuth_SignAccess_Call) RunAndReturn(run func(string, string) (string, error)) *MockAuth_SignAccess_Call {
	_c.Call.Return(run)
	return _c
}

// SignRefresh provides a mock function with given fields: userID, sessionID
func (_m *MockAuth) SignRefresh(userID string, sessionID string) (string, error) {
	ret := _m.Called(userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for SignRefresh")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(userID, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuth_SignRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignRefresh'
type MockAuth_SignRefresh_Call struct {
	*mock.Call
}

// SignRefresh is a helper method to define mock.On call
//   - userID string
//   - sessionID string
func (_e *MockAuth_Expecter) SignRefresh(userID interface{}, sessionID interface{}) *MockAuth_SignRefresh_Call {
	return &MockAuth_SignRefresh_Call{Call: _e.mock.On("SignRefresh", userID, sessionID)}
}

func (_c *MockAuth_SignRefresh_Call) Run(run func(userID string, sessionID string)) *MockAuth_SignRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuth_SignRefresh_Call) Return(_a0 string, _a1 error) *MockAuth_SignRefresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuth_SignRefresh_Call) RunAndReturn(run func(string, string) (string, error)) *MockAuth_SignRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
